# Generated by Django 6.0.5 on 2026-06-13 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='moyen_paiement',
            field=models.CharField(choices=[('orange_money', 'Orange Money CI'), ('mtn_momo', 'MTN MoMo'), ('wave', 'Wave'), ('moov_africa', 'Moov Africa')], max_length=20),
        ),
        migrations.CreateModel(
            name='CircuitTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duree_jours', models.PositiveIntegerField(default=1)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('niveau', models.CharField(choices=[('facile', 'Facile'), ('modere', 'Modéré'), ('difficile', 'Difficile')], default='facile', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='circuits/')),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regions', models.ManyToManyField(blank=True, related_name='circuits', to='apptourism.region')),
            ],
        ),
        migrations.CreateModel(
            name='EvenementTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_event', models.CharField(choices=[('festival', 'Festival'), ('masque', 'Fête des Masques'), ('igname', 'Fête des Ignames'), ('dipri', 'Fête du Dipri'), ('masa', 'MASA'), ('exposition', 'Exposition'), ('concert', 'Concert'), ('culturel', 'Événement Culturel'), ('sportif', 'Événement Sportif'), ('gastronomie', 'Événement Gastronomique'), ('religieux', 'Événement Religieux'), ('autre', 'Autre')], default='culturel', max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('prix_entree', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='apptourism.region')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='apptourism.sitetouristique')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='GuideTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('langues_parlees', models.CharField(help_text='Ex: Français, Anglais, Espagnol, Chinois, Allemand', max_length=255)),
                ('specialites', models.TextField(blank=True, help_text='Ex: Nature, Histoire, Gastronomie')),
                ('tarif_journalier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annees_experience', models.PositiveIntegerField(default=0)),
                ('est_certifie', models.BooleanField(default=False)),
                ('est_disponible', models.BooleanField(default=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regions_couvertes', models.ManyToManyField(blank=True, related_name='guides', to='apptourism.region')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_guide', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gamme', models.CharField(choices=[('economique', 'Économique'), ('standard', 'Standard'), ('superieur', 'Supérieur'), ('luxe', 'Luxe')], default='standard', max_length=20)),
                ('prix_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='apptourism.region')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('type_cuisine', models.CharField(choices=[('maquis', 'Maquis (resto ivoirien typique)'), ('ivoirienne', 'Cuisine Ivoirienne'), ('garba', 'Garba (attiéké + thon)'), ('africaine', 'Cuisine Africaine'), ('libanaise', 'Cuisine Libanaise'), ('internationale', 'Cuisine Internationale'), ('rapide', 'Restauration Rapide'), ('fruits_mer', 'Fruits de Mer'), ('vegetarienne', 'Végétarienne')], default='ivoirienne', max_length=30)),
                ('specialites', models.TextField(blank=True)),
                ('prix_moyen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='apptourism.region')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transport', models.CharField(choices=[('woro_woro', 'Woro-woro (taxi collectif)'), ('gbaka', 'Gbaka (minibus)'), ('sotra', 'SOTRA (bus urbain Abidjan)'), ('taxi_lagune', 'Taxi-lagune (Abidjan)'), ('car_interurb', 'Car interurbain (longue distance)'), ('bateau', 'Bateau / Pirogue'), ('vol_interieur', 'Vol intérieur'), ('moto', 'Moto-taxi (Zemidjan)')], max_length=20)),
                ('compagnie', models.CharField(blank=True, max_length=200)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_minutes', models.PositiveIntegerField(help_text='Durée estimée du trajet en minutes')),
                ('horaires', models.TextField(blank=True, help_text='Ex: Départs à 6h, 9h, 14h')),
                ('telephone_contact', models.CharField(blank=True, max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('region_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports_arrivee', to='apptourism.region')),
                ('region_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports_depart', to='apptourism.region')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('description_etape', models.TextField(blank=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='apptourism.circuittouristique')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_circuit', to='apptourism.sitetouristique')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('circuit', 'ordre')},
            },
        ),
    ]
