# Generated by Django 6.0.5 on 2026-06-14 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptourism', '0002_alter_paiement_moyen_paiement_circuittouristique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='proprietaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'proprietaire'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_hotels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='proprietaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'proprietaire'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
